# Generated by Django 4.2.7 on 2023-11-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='descount',
            new_name='discount',
        ),
    ]
