# Generated by Django 4.2.7 on 2023-11-03 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zipcode'),
    ]

    operations = [
        migrations.RunSQL(
            """
                INSERT into store_collection (title)
                    values ("Electronics");
            """,

            """
                DELETE FROM store_collection
                    where title = "Electronics";
            """
        )
    ]
